version = 1

exclude_patterns = [
  "**/node_modules/**",
  "**/dist/**",
  "**/.angular/**",
  "**/coverage/**",
]

test_patterns = [
  "HeatMapsFront/src/**/*.spec.ts",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser", "nodejs"]
  dialect = "typescript"
  cyclomatic_complexity_threshold = "high"
